spring:
  datasource:
    url: jdbc:mysql://localhost:3306/salary?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT&allowMultiQueries=true
    username: root
    password: 8880
    driver-class-name: com.mysql.cj.jdbc.Driver