server:
  port: 5678
  servlet:
    context-path: /salary

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/salary?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT&allowMultiQueries=true
    username: root
    password: 8880
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  config-location: classpath:mybatis-config.xml # mybatis配置文件所在路径
  mapper-locations: classpath:com/salary/mapper/*.xml # mapper映射文件