server:
  port: 5678
  servlet:
    context-path: /salary

spring.main.allow-bean-definition-overriding: true
# 解决多个项目部署在tomcat报错：javax.management.InstanceAlreadyExistsException:com.zaxxer.hikari:name=mallDataSource
spring:
  profiles:
    active: prod # 生产环境
  jmx:
    enabled: false # spring.jmx.default-domain=project1

mybatis:
  config-location: classpath:mybatis-config.xml # mybatis配置文件所在路径